"""init migration2

Revision ID: 2bbfad597e47
Revises: f9a387afa6eb
Create Date: 2023-07-07 20:51:26.711092

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2bbfad597e47'
down_revision = 'f9a387afa6eb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
