"""init migration2

Revision ID: 8abe737029a7
Revises: 5f55d3f66ad7
Create Date: 2023-07-07 21:35:26.458785

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8abe737029a7'
down_revision = '5f55d3f66ad7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
