"""init migration2

Revision ID: f9a387afa6eb
Revises: 
Create Date: 2023-07-07 20:48:20.697498

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9a387afa6eb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('participants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prizes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('promos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('prizes', sa.Integer(), nullable=False),
    sa.Column('participants', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['participants'], ['participants.id'], ),
    sa.ForeignKeyConstraint(['prizes'], ['prizes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('winners',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('winner', sa.Integer(), nullable=False),
    sa.Column('prize', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['prize'], ['prizes.id'], ),
    sa.ForeignKeyConstraint(['winner'], ['participants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('winners')
    op.drop_table('promos')
    op.drop_table('prizes')
    op.drop_table('participants')
    # ### end Alembic commands ###
